import { CausalChain } from '@sentinelops/graph';

export function buildNarrativePrompt(chain: CausalChain): string {
  const causeCount = chain.probableCauses?.length ?? 0;
  const affectedCount = chain.blastRadius?.length ?? 0;
  const topCause = chain.probableCauses?.[0];

  return `You are an expert Site Reliability Engineer (SRE) analyzing a production incident.
Your job is to write a concise, accurate incident summary for an on-call engineer who needs to act immediately.

## Input Data

### Probable Causes (ranked by confidence, highest first)
${JSON.stringify(chain.probableCauses, null, 2)}

### Blast Radius (${affectedCount} service(s) affected)
${JSON.stringify(chain.blastRadius, null, 2)}

### Incident Timeline (chronological)
${JSON.stringify(chain.timeline, null, 2)}

## Your Task

Produce a response in **strict JSON** matching EXACTLY this schema. No extra keys. No markdown fences.

{
  "summary": "<2-3 sentences: what failed, the most probable root cause with confidence %, and the blast radius impact>",
  "remediation": {
    "primary": "<single most important immediate action>",
    "steps": ["<step 1>", "<step 2>", "<step 3>", "<step 4>"]
  },
  "postmortem": {
    "draft": "<3-5 sentence outline covering: what happened, contributing factors, customer impact, and one prevention action item>",
    "generatedAt": "${new Date().toISOString()}"
  }
}

## Hard Rules
1. Output raw JSON only — no \`\`\`json, no markdown, no extra text before or after the JSON object.
2. Ground every claim in the provided data. If confidence is below 50%, use "possibly" or "may have". Above 80%, use "likely" or "probable".
3. Never invent service names, error codes, or events not present in the input.
4. remediation.steps must be ordered: diagnose first, then mitigate, then verify, then communicate.
5. If ${causeCount} probable causes exist and the top confidence is ${topCause?.confidence ?? 0}, reflect that uncertainty accurately.
6. summary must mention: the affected service(s), the probable cause service, and the number of downstream services impacted.`;
}

export function buildPostmortemPrompt(chain: CausalChain, resolution: string): string {
  const incidentId = chain.incidentId ?? 'UNKNOWN';
  const affectedServices = (chain.blastRadius ?? []).map((b: { service: string }) => b.service).join(', ') || 'unknown';

  return `You are a senior SRE writing a formal postmortem document for incident ${incidentId}.
This document will be shared with engineering leadership and the broader team.

## Incident Data

### Causal Chain
${JSON.stringify(chain, null, 2)}

### Resolution
${resolution}

## Instructions

Write a complete postmortem in **Markdown** with the following sections IN ORDER:

# Postmortem: Incident ${incidentId}

## Executive Summary
Two sentences max. State what failed and the business impact.

## Timeline
A chronological bullet list of events from the timeline data above. Use format: \`HH:MM UTC — event description\`.

## Root Cause Analysis
- **Primary cause:** (from probableCauses[0], include confidence %)
- **Contributing factors:** (from remaining probableCauses if any)
- **Why it wasn't caught earlier:** (infer from timeline gaps if visible)

## Impact Assessment
- Services affected: ${affectedServices}
- Blast radius: (summarize from blastRadius data)
- Estimated duration: (from first to last timeline event)

## Resolution
${resolution}

## Action Items
List exactly 3–5 concrete, assignable action items to prevent recurrence. Format:
| # | Action | Owner | Due |
|---|--------|-------|-----|
| 1 | ... | Team | 1 week |

## Lessons Learned
One paragraph. What went well, what went wrong, what the team will do differently.

---
*Generated by SentinelOps AI on ${new Date().toISOString()}*

## Rules
- Use ONLY data from the provided incident data and resolution
- Do not fabricate metrics, percentages, or SLA numbers unless they appear in the input
- Keep the tone factual and blameless
- All times must come from the timeline data`;
}

